version: "2"

services:
  reg_system:
    image: awadieudonne/reg_system
    ports:
      - 80:3000
    command: npm run dev
    volumes:
      - .:/reg_system/
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:awa@localhost:5432/reg_system
      - PORT=3000
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=awa
      - POSTGRES_DB=reg_system
